# -*- coding: utf-8 -*-
"""Edu_kg_gliner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13U8c56Ws08HGZMrwz-DTJAAp4jB5TIKe

## Cell 0 — Install dependencies
Run once per Colab session.
"""

# -- Core parsing deps --------------------------------------------------------
!pip install marker-pdf -q
!pip install pytesseract pillow pymupdf -q
!apt-get install -y tesseract-ocr -q

# -- NLP / ML deps ------------------------------------------------------------
!pip install sentence-transformers spacy -q
!python -m spacy download en_core_web_sm -q

# -- GLiNER (replaces SIFRank / spaCy noun chunks in Step 3) -----------------
!pip install gliner -q

# -- LLM / LangChain deps -----------------------------------------------------
!pip install langchain langchain-groq -q

# -- Sanity check -------------------------------------------------------------
import importlib, subprocess, sys
for pkg in ["marker", "pytesseract", "fitz", "PIL",
            "sentence_transformers", "spacy", "gliner", "langchain_groq"]:
    ok = importlib.util.find_spec(pkg) is not None
    print(f"{'OK' if ok else 'MISSING':6s}  {pkg}")

res = subprocess.run(["tesseract", "--version"], capture_output=True, text=True)
print(f"{'OK' if res.returncode == 0 else 'MISSING':6s}  tesseract",
      res.stdout.splitlines()[0] if res.returncode == 0 else "")

print("\nAll dependencies installed.")

"""## Cell 1 — Upload PDF
Upload the lecture slide PDF you want to process.
"""

from google.colab import files
from pathlib import Path

uploaded = files.upload()
PDF_PATH = list(uploaded.keys())[0]
DOC_ID   = Path(PDF_PATH).stem          # used as document identifier throughout
STEM     = DOC_ID                       # base name for all output files

print(f"Uploaded : {PDF_PATH}")
print(f"Doc ID   : {DOC_ID}")

"""## Step 1 — Marker PDF Parsing

Uses **Marker** (deep-learning PDF parser) to convert each slide into structured
markdown. For slides where Marker finds no text (image-only), a Tesseract OCR
fallback renders the page at 3× zoom and recovers text.

**Output:** `SlideMarkdown` per page — `slide_id`, `page_number`, `raw_markdown`, `doc_id`.

> First run downloads ~4 GB of Marker model weights — allow ~5 minutes.
"""

import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List

import fitz
import pytesseract
from PIL import Image

from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict

# ── Config ────────────────────────────────────────────────────────────────────
PAGE_SEP = "\n\n<<<MARKER_PAGE_BREAK>>>\n\n"
# PDF_PATH, DOC_ID, STEM defined in the upload cell above.

# ── Data model ────────────────────────────────────────────────────────────────
@dataclass
class SlideMarkdown:
    slide_id:     str
    page_number:  int
    raw_markdown: str
    doc_id:       str

# ── Helper: empty-page check ─────────────────────────────────────────────────
def _is_empty_page(markdown: str) -> bool:
    """
    Return True when Marker found no real text on a page.

    FIX S1-2: strips {N} slide-number tags before the length check so that a
    page containing only e.g. '{3}' is correctly identified as empty.
    """
    cleaned = markdown.strip()
    if not cleaned:
        return True
    # Strip image markdown, basic formatting, and {N} slide-number tags
    text_only = re.sub(r"!\[.*?\]\(.*?\)", "", cleaned)
    text_only = re.sub(r"\{\d+\}",         "", text_only)   # FIX S1-2
    text_only = re.sub(r"[#>\-\*\|]",      "", text_only).strip()
    return len(text_only) < 10

# ── Helper: duplicate-page detection (FIX S1-1) ──────────────────────────────
def _word_set(markdown: str) -> set:
    """Lower-cased word tokens, stripped of punctuation."""
    return set(re.sub(r"[^a-z0-9]", " ", markdown.lower()).split())

def _is_duplicate_page(
    new_md: str,
    existing_slides: List[SlideMarkdown],
    window: int = 2,
    threshold: float = 0.50,
) -> bool:
    """
    Return True if new_md is substantially similar to one of the last `window`
    slides already added.

    Uses Jaccard similarity on word sets.  A threshold of 0.50 catches the
    OCR-title / Marker-title duplicate pattern (confirmed Jaccard = 0.520 on
    real data) while leaving genuinely different slides untouched.

    Guards:
    - Requires at least 5 distinct words in the new page (avoids false-positives
      on near-empty decorative slides).
    - Only compares against the most recent `window` slides, not the whole deck.
    """
    if not existing_slides:
        return False
    new_words = _word_set(new_md)
    if len(new_words) < 5:
        return False
    for prev in existing_slides[-window:]:
        prev_words = _word_set(prev.raw_markdown)
        if not prev_words:
            continue
        intersection = len(new_words & prev_words)
        union        = len(new_words | prev_words)
        if union > 0 and intersection / union >= threshold:
            return True
    return False

# ── Helper: OCR fallback ──────────────────────────────────────────────────────
def _ocr_page(doc: fitz.Document, page_number: int) -> str:
    """Render page at 3× zoom and run Tesseract (page_number is 1-indexed)."""
    page = doc[page_number - 1]
    mat  = fitz.Matrix(3, 3)
    pix  = page.get_pixmap(matrix=mat)
    img  = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
    return pytesseract.image_to_string(img, config="--psm 6").strip()

# ── Main pipeline ─────────────────────────────────────────────────────────────
print(f"Opening '{PDF_PATH}' to establish actual page count …")
doc = fitz.open(PDF_PATH)
actual_page_count = len(doc)
print(f"PDF contains exactly {actual_page_count} pages.")

print("Loading Marker models (first run downloads ~4 GB — allow ~5 min) …")
model_dict = create_model_dict()
converter  = PdfConverter(
    artifact_dict=model_dict,
    config={"paginate_output": True, "page_separator": PAGE_SEP},
)
rendered      = converter(PDF_PATH)
full_markdown = rendered.markdown
raw_pages     = [p.strip() for p in full_markdown.split(PAGE_SEP)]

slides_md:  List[SlideMarkdown] = []
ocr_count   = 0
skip_count  = 0

for idx in range(1, actual_page_count + 1):
    page_md = raw_pages[idx - 1].strip() if (idx - 1) < len(raw_pages) else ""

    # OCR fallback when Marker returns nothing
    if _is_empty_page(page_md):
        print(f"  [slide_{idx:03d}] Marker: no text — running OCR …")
        ocr_text = _ocr_page(doc, idx)
        if ocr_text:
            page_md = "\n".join(
                f"> OCR: {line}"
                for line in ocr_text.splitlines()
                if line.strip()
            )
            print(f"  [slide_{idx:03d}] OCR recovered {len(ocr_text):,} chars")
            ocr_count += 1
        else:
            print(f"  [slide_{idx:03d}] OCR found nothing — slide may be decorative, skipping")
            page_md = ""

    # FIX S1-1: skip page if it is a near-duplicate of a recently added slide
    if page_md and _is_duplicate_page(page_md, slides_md):
        print(f"  [slide_{idx:03d}] Duplicate of previous slide detected — skipping")
        skip_count += 1
        continue

    page_md = re.sub(r"\n{3,}", "\n\n", page_md)

    if not page_md:
        continue

    slides_md.append(SlideMarkdown(
        slide_id    = f"slide_{idx:03d}",
        page_number = idx,
        raw_markdown= page_md,
        doc_id      = DOC_ID,
    ))

doc.close()

print(f"\nStep 1 complete: {len(slides_md)} slides "
      f"({ocr_count} used OCR fallback, {skip_count} duplicates skipped)")

# ── Save ──────────────────────────────────────────────────────────────────────
STEP1_FILE = f"{STEM}_step1_parsed.json"
with open(STEP1_FILE, "w", encoding="utf-8") as f:
    json.dump([asdict(s) for s in slides_md], f, ensure_ascii=False, indent=2)
print(f"Saved: {STEP1_FILE} ({Path(STEP1_FILE).stat().st_size:,} bytes)")

SHOW_SLIDES = [1, 2, 3]
SHOW_FULL   = False

from IPython.display import Markdown, display

print(f"\nTotal slides: {len(slides_md)}\n")
for slide in slides_md:
    if slide.page_number not in SHOW_SLIDES:
        continue
    display(Markdown(f"---\n### Slide {slide.page_number} — `{slide.slide_id}`\n---"))
    md = slide.raw_markdown
    print(md if SHOW_FULL else (md[:500] + ("…" if len(md) > 500 else "")))

from google.colab import files as _files
_files.download(STEP1_FILE)
print(f"Downloading {STEP1_FILE} …")

# ── Download Step 1 output ─────────────────────────────────────────────────
from google.colab import files as _files
_files.download(STEP1_FILE)
print(f"Downloading {STEP1_FILE} ...")

"""## Step 2 — Markdown Preprocessor

Four stages applied to the raw markdown from Step 1:

1. **Structural parsing** — lines routed into typed buckets: headings, bullets, table cells, captions, body text
2. **Noise removal** — page numbers, copyright lines, URLs, image tags discarded
3. **Cross-slide repetition filter** — blocks appearing on >50% of slides removed (recurring headers/footers)
4. **Assembly** — buckets joined into `clean_text`; `heading_phrases` stored for Step 3 boost

OCR-recovered lines (prefixed `> OCR:`) are re-classified into proper buckets instead of being dumped into captions.

**Output:** `SlideContent` per slide.
"""

import re
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import List

# ── Data model ────────────────────────────────────────────────────────────────
@dataclass
class SlideContent:
    slide_id:        str
    page_number:     int
    doc_id:          str
    headings:        List[str] = field(default_factory=list)
    body_text:       List[str] = field(default_factory=list)
    bullets:         List[str] = field(default_factory=list)
    table_cells:     List[str] = field(default_factory=list)
    captions:        List[str] = field(default_factory=list)
    code_lines:      List[str] = field(default_factory=list)
    heading_phrases: List[str] = field(default_factory=list)
    clean_text:      str       = ""
    ocr_applied:     bool      = False

# ── Noise patterns ────────────────────────────────────────────────────────────
_NOISE_PATTERNS = [
    re.compile(r"^\s*page\s+\d+\s*(of\s+\d+)?\s*$",  re.IGNORECASE),
    re.compile(r"^\s*\d+\s*$"),
    # FIX S2-1: was r"^[cC].*" — matched ANY text starting with C/c.
    # Now targets only genuine copyright notices.
    re.compile(r"^(?:©|\(c\)|copyright\b)",           re.IGNORECASE),
    re.compile(r"^\s*(references|bibliography)\s*$",   re.IGNORECASE),
    re.compile(r"https?://\S+"),
    re.compile(r"^\s*\[\d+\]"),
    re.compile(r"^!\[.*?\]\(.*?\)$"),
    re.compile(r"^quiz\s*:",                           re.IGNORECASE),
    re.compile(r"^\{\d+\}$"),                          # {N} slide-number tags
    re.compile(
        r"^(input|output|legend|infrastructure)"
        r"(\s+replaced.*|\s+kept.*|\s+storage.*)?$",
        re.IGNORECASE,
    ),
]

def _is_noise(text: str) -> bool:
    t = text.strip()
    return bool(t) and any(p.match(t) for p in _NOISE_PATTERNS)

# ── Code-line detector ────────────────────────────────────────────────────────
# FIX S2-3: removed '<' and '>' from code_chars — they fire on inequality
# lists and prose type-parameter examples, producing false positives.
_CODE_CHARS = frozenset("{}();=[]")

def _is_code_line(text: str) -> bool:
    """
    Heuristic classifier: return True when a text fragment looks like source
    code rather than natural-language prose.

    Changes vs original
    -------------------
    S2-3  '<' and '>' removed from _CODE_CHARS (see module docstring).
    S2-2  func-call rule threshold raised to n >= 3 AND capped at
          word_count <= 8 so long prose sentences are not caught.
    S2-4  camelCase rule now requires fewer than 2 commas so that token
          enumerations like '<, >, compareTo, …' are not misclassified.
    S2-6  New dot-access rule for short identifier.property expressions.
    """
    t = text.strip()
    if not t:
        return False
    if t.startswith("```"):
        return True

    n          = sum(1 for c in t if c in _CODE_CHARS)
    word_count = len(t.split())

    # Primary signal: high density of code punctuation
    if len(t) > 5 and n / len(t) > 0.08:
        return True

    # camelCase identifier  (FIX S2-4: exclude comma-separated token lists)
    if re.search(r"\b[a-z]+[A-Z][a-zA-Z]+\b", t):
        if word_count <= 5 and t.count(",") < 2:
            return True

    # snake_case identifier
    if re.search(r"\b[a-z]+_[a-z]+\b", t):
        return True

    # Comparison / assignment operators in spacing context
    if re.search(r"\s(==|!=|<=|>=|&&|\|\||:=|->|=>)\s", t):
        return True

    # Line terminators typical of C-family code
    if t.endswith((";", "{", "}")):
        return True

    # Comment prefixes
    if re.match(r"^\s*(//|#\s|--|/\*|\*\s)", t):
        return True

    # Method / function call  (FIX S2-2: n >= 3 AND word_count <= 8)
    if re.search(r"\b\w{2,}\(", t) and n >= 3 and word_count <= 8:
        return True

    # Constructor declaration
    if re.match(r"^(default\s+)?constructor\s+\w+\s*\(", t, re.IGNORECASE):
        return True

    # Python dunder method
    if re.match(r"^__\w+__\s*\(", t):
        return True

    # FIX S2-6: dot-notation access on very short lines  (e.g. scores.length)
    if re.search(r"\b[a-z]\w*\.[a-z]\w*\b", t) and word_count <= 3:
        return True

    return False

# ── Inline markdown stripper ──────────────────────────────────────────────────
_INLINE_MD = re.compile(
    r"(\*\*|__)(.*?)\1|(\*|_)(.*?)\3|`([^`]+)`|~~(.*?)~~|\[([^\]]+)\]\([^)]+\)",
    re.DOTALL,
)

def _strip_inline(text: str) -> str:
    prev = None
    while prev != text:
        prev = text
        text = _INLINE_MD.sub(
            lambda m: next(
                g for g in m.groups()
                if g is not None and g not in ("**", "__", "*", "_")
            ),
            text,
        )
    return text.strip()

# ── Bullet-marker regex ───────────────────────────────────────────────────────
# Covers ASCII bullets (- * +) and Unicode geometric shapes / dingbats used
# by Beamer and other academic PDF tools as slide bullet markers.
_BULLET_RE = re.compile(
    r"^\s*[-*+]\s*(?:[\u2022\u25A0-\u25FF\u2700-\u27BF]\s*)?|"
    r"^\s*[\u2022\u25A0-\u25FF\u2700-\u27BF]\s+"
)
_BEAMER_BULLET_RE = re.compile(r"^[\u2022\u25A0-\u25FF\u2700-\u27BF]\s*")

# ── OCR noise detector ────────────────────────────────────────────────────────
def _is_ocr_noise(text: str) -> bool:
    t = text.strip()
    if not t or len(t) < 4:
        return True
    words = t.split()
    if len(words) == 1 and not words[0].isalpha():
        return True
    non_ascii = sum(1 for c in t if ord(c) > 127)
    if non_ascii / len(t) > 0.1:
        return True
    letters = sum(1 for c in t if c.isalpha())
    if len(t) > 5 and letters / len(t) < 0.4:
        return True
    return False

# ── FIX S2-5: prose-label detector for mixed code/prose fences ───────────────
def _is_prose_label(line: str) -> bool:
    """
    Return True when a line inside a ``` code fence is actually a prose bullet
    label (e.g. '• construction', '• storing a value') that should be routed
    to bullets rather than code_lines.

    Criteria:
    - Starts with a bullet marker (ASCII or Unicode) or '•'
    - After stripping the marker, contains at least one word
    - Contains zero _CODE_CHARS (no assignment, parens, brackets, etc.)

    This is intentionally strict to avoid accidentally routing real code lines
    (which will always contain at least one code char) to the wrong bucket.
    """
    s = line.strip()
    is_bullet = bool(_BULLET_RE.match(s)) or s.startswith("•")
    if not is_bullet:
        return False
    inner = _BULLET_RE.sub("", s).lstrip("•").strip()
    if not inner:
        return False
    return sum(1 for c in inner if c in _CODE_CHARS) == 0

# ── OCR line re-classifier ────────────────────────────────────────────────────
def _classify_ocr_line(text: str, sc: SlideContent) -> None:
    """Re-classify a single OCR-recovered line into the appropriate bucket."""
    stripped = text.strip()
    if not stripped or _is_noise(stripped) or _is_ocr_noise(stripped):
        return
    if _is_code_line(stripped):
        sc.code_lines.append(stripped)
        return
    if stripped.startswith("#"):
        inner = re.sub(r"^#+\s*", "", stripped).strip()
        if inner:
            sc.headings.append(inner)
            sc.heading_phrases.append(inner)
    elif re.match(r"^[-*+¢—>]\s+", stripped):
        inner = _BULLET_RE.sub("", stripped).strip()
        if inner:
            sc.bullets.append(inner)
    elif stripped.startswith("|") and stripped.endswith("|"):
        if not re.match(r"^\|[\s\-\|]+\|$", stripped):
            cells = [c.strip() for c in stripped.split("|") if c.strip()]
            sc.table_cells.extend(cells)
    else:
        sc.body_text.append(stripped)

# ── Stage 1+2: parse a single slide ──────────────────────────────────────────
def _parse_slide(slide_md: SlideMarkdown) -> SlideContent:
    sc = SlideContent(
        slide_id    = slide_md.slide_id,
        page_number = slide_md.page_number,
        doc_id      = slide_md.doc_id,
    )

    lines       = slide_md.raw_markdown.splitlines()
    in_fence    = False   # are we currently inside a ``` code fence?

    for line in lines:
        s = line.strip()
        if not s:
            continue

        # ── Code fence toggle ─────────────────────────────────────────────────
        if s.startswith("```"):
            in_fence = not in_fence
            continue

        # ── Inside a code fence ───────────────────────────────────────────────
        if in_fence:
            # FIX S2-5: route prose bullet labels to bullets, not code_lines
            if _is_prose_label(line):
                inner = _BULLET_RE.sub("", s).lstrip("•").strip()
                inner = _strip_inline(inner)
                if inner and not _is_noise(inner):
                    sc.bullets.append(inner)
            else:
                if s and not _is_noise(s):
                    sc.code_lines.append(s)
            continue

        # ── Headings ──────────────────────────────────────────────────────────
        if s.startswith("#"):
            text = _strip_inline(re.sub(r"^#+\s*", "", s))
            if text and not _is_noise(text):
                sc.headings.append(text)
                sc.heading_phrases.append(text)

        # ── Blockquotes: captions or OCR-recovered lines ──────────────────────
        # FIX S2-OCR: this branch MUST appear before the bullet regex because
        # '>' is included in the bullet character class r'^[-*¢—>]\s+'.
        # If the bullet branch fired first, '> OCR: ...' lines would be routed
        # to bullets with the "OCR: " prefix intact instead of being properly
        # re-classified by _classify_ocr_line().
        elif s.startswith(">"):
            inner = re.sub(r"^>\s*", "", s).strip()
            if inner.startswith("OCR:"):
                sc.ocr_applied = True
                _classify_ocr_line(inner[4:].strip(), sc)
            else:
                text = _strip_inline(inner)
                if text and not _is_noise(text):
                    sc.captions.append(text)

        # ── Standard markdown bullets (- * ¢ —) ──────────────────────────────
        # Note: '>' intentionally removed from this pattern — handled above.
        elif re.match(r"^[-*¢—]\s+", s) and not s.startswith(("**", "*a", "*b", "*c")):
            m    = re.match(r"^[-*¢—]\s+(.+)", s)
            text = _strip_inline(m.group(1)) if m else ""
            if text and not _is_noise(text):
                if _is_code_line(text):
                    sc.code_lines.append(text)
                else:
                    sc.bullets.append(text)

        # ── Beamer / Unicode geometric shape bullets ──────────────────────────
        elif _BEAMER_BULLET_RE.match(s):
            text = _strip_inline(_BULLET_RE.sub("", s)).strip()
            text = _BULLET_RE.sub("", text).strip()
            if text and not _is_noise(text):
                if _is_code_line(text):
                    sc.code_lines.append(text)
                else:
                    sc.bullets.append(text)

        # ── Table rows ────────────────────────────────────────────────────────
        elif s.startswith("|") and s.endswith("|"):
            cells = [_strip_inline(c.strip()) for c in s.split("|") if c.strip()]
            if all(re.fullmatch(r"[-:]+", c) for c in cells):
                continue   # markdown separator row
            # FIX S2-TABLE-HEADER: Skip pure header rows — rows where every
            # cell is very short (≤ 2 words) and looks like a column label
            # (e.g. "Operation | Description", "Method name | Description").
            # These create noise keyphrases like "operation" and cause wrong
            # triples like "dequeue isPartOf operation".
            # A header row has: all cells ≤ 2 words, all cells title-case or
            # all-caps, and no cell contains digits or parentheses.
            def _looks_like_header_cell(cell: str) -> bool:
                words = cell.split()
                if len(words) > 3:
                    return False
                if any(c.isdigit() or c in "()" for c in cell):
                    return False
                return True
            if cells and all(_looks_like_header_cell(c) for c in cells):
                continue   # skip header row
            sc.table_cells.extend(c for c in cells if c and not _is_noise(c))

        # ── Body text (everything else) ───────────────────────────────────────
        else:
            text = _strip_inline(s)
            if not text or _is_noise(text):
                continue
            if _is_code_line(text):
                sc.code_lines.append(text)
            else:
                sc.body_text.append(text)

    return sc

# ── Stage 3: cross-slide repetition filter ───────────────────────────────────
def _cross_slide_filter(contents: List[SlideContent]) -> List[SlideContent]:
    total = len(contents)
    if total < 5:
        print(f"Cross-slide filter skipped (only {total} slides — need ≥ 5)")
        return contents
    threshold = total * 0.5
    counts: Counter = Counter()
    for sc in contents:
        seen: set = set()
        for bucket in (sc.headings, sc.body_text, sc.bullets, sc.table_cells, sc.captions):
            for t in bucket:
                if t not in seen:
                    counts[t] += 1
                    seen.add(t)
    noise = {t for t, c in counts.items() if c > threshold}
    if noise:
        print(f"Cross-slide filter removed {len(noise)} repeated block(s):")
        for n in sorted(noise):
            print(f"  '{n[:80]}'")
    else:
        print("Cross-slide filter: nothing removed")
    for sc in contents:
        sc.headings    = [t for t in sc.headings    if t not in noise]
        sc.body_text   = [t for t in sc.body_text   if t not in noise]
        sc.bullets     = [t for t in sc.bullets     if t not in noise]
        sc.table_cells = [t for t in sc.table_cells if t not in noise]
        sc.captions    = [t for t in sc.captions    if t not in noise]
    return contents

# ── Stage 4: assemble clean_text ─────────────────────────────────────────────
def _assemble(sc: SlideContent) -> None:
    parts        = sc.headings + sc.body_text + sc.bullets + sc.table_cells + sc.captions
    sc.clean_text = " ".join(parts).strip()

# ── Run all stages ────────────────────────────────────────────────────────────
print("Stage 1+2: parsing and noise removal …")
slide_contents: List[SlideContent] = [_parse_slide(s) for s in slides_md]

print("Stage 3: cross-slide repetition filter …")
slide_contents = _cross_slide_filter(slide_contents)

print("Stage 4: assembling clean_text …")
for sc in slide_contents:
    _assemble(sc)

content_slides = [sc for sc in slide_contents if sc.clean_text.strip()]
print(f"\nStep 2 complete: {len(content_slides)}/{len(slide_contents)} slides have content")
print(f"  OCR applied on : {sum(1 for s in content_slides if s.ocr_applied)} slide(s)")
print(f"  Slides with bullets: {sum(1 for s in content_slides if s.bullets)}")

# ── Save ──────────────────────────────────────────────────────────────────────
STEP2_FILE = f"{STEM}_step2_preprocessed.json"
with open(STEP2_FILE, "w", encoding="utf-8") as f:
    json.dump([asdict(s) for s in slide_contents], f, ensure_ascii=False, indent=2)
print(f"Saved  : {STEP2_FILE} ({Path(STEP2_FILE).stat().st_size:,} bytes)")

from IPython.display import Markdown, display

print(f"\n{'slide_id':<12} {'head':>4} {'body':>4} {'bull':>4} "
      f"{'tbl':>4} {'cap':>4} {'code':>4} {'OCR':>4}  clean_text (first 120 chars)")
print("-" * 112)
for sc in content_slides:
    flag = "Y" if sc.ocr_applied else "-"
    print(f"{sc.slide_id:<12} {len(sc.headings):>4} {len(sc.body_text):>4} "
          f"{len(sc.bullets):>4} {len(sc.table_cells):>4} {len(sc.captions):>4} "
          f"{len(sc.code_lines):>4} {flag:>4}  {sc.clean_text[:120]}")

print("\n" + "=" * 80)
print("Detailed view of first 3 content slides")
for sc in content_slides[:3]:
    display(Markdown(f"---\n### {sc.slide_id}  (page {sc.page_number})"))
    print(f"Headings    : {sc.headings}")
    print(f"Bullets     : {sc.bullets[:5]}")
    print(f"Body        : {sc.body_text[:2]}")
    print(f"Table cells : {sc.table_cells[:3]}")
    print(f"Code lines  : {sc.code_lines[:2]}")
    print(f"OCR applied : {sc.ocr_applied}")
    print(f"clean_text  : {sc.clean_text[:300]}")

from google.colab import files as _files
_files.download(STEP2_FILE)
print(f"Downloading {STEP2_FILE} …")

# ── Download Step 2 output ─────────────────────────────────────────────────
from google.colab import files as _files
_files.download(STEP2_FILE)
print(f"Downloading {STEP2_FILE} ...")

import json, re, os, time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Dict, Optional

import spacy
from gliner import GLiNER
from sentence_transformers import SentenceTransformer, util as st_util

# -- Config -------------------------------------------------------------------
GLINER_MODEL           = "urchade/gliner_large-v2.1"  # full large on T4 GPU
GLINER_THRESHOLD       = 0.35   # lower = more recall; large model is precise enough
DEDUP_SIM_THRESHOLD    = 0.85   # SBERT cosine threshold for near-duplicate removal
KEYPHRASE_MAX          = 25     # max keyphrases per slide
HEADING_BOOST          = 0.15   # score bonus for heading-sourced phrases

# Scores by extraction source (used in Step 5 weighting):
#   GLiNER confident hit  : actual GLiNER score (0.35 – 1.0)
#   LLM fallback          : 0.40  (above spaCy, below GLiNER confident)
# spaCy fallback removed — replaced by LLM fallback (cleaner, context-aware)

# -- Generic keyphrase quality filters ----------------------------------------
# Single-word stopwords that carry no educational signal on their own.
# Domain terms like "list", "map", "set", "type" are deliberately NOT here.
_KP_GENERIC_WORDS = frozenset({
    "the", "this", "that", "these", "those", "some", "any",
    "each", "other", "another", "same", "such", "both", "all",
    "one", "two", "three", "four", "first", "second", "third",
    "use", "used", "using", "used to", "make", "made", "get",
    "given", "certain", "following", "above", "below", "per",
    "based", "etc", "e.g", "i.e", "note", "example", "part",
    "case", "way", "ways", "form", "time", "times", "place",
    "thing", "things", "item", "items", "value", "values",
    "number", "numbers", "order", "fact", "result", "results",
    "amount", "level", "type", "types", "kind", "kinds",
})

# Instructional slide-label starters — phrases starting with these AND ≥ 4
# words are structural slide labels, not educational concepts.
_LABEL_STARTERS = (
    "to ", "any ", "how ", "what ", "when ", "where ", "why ",
    "see ", "let ", "note ", "given ", "recall ", "consider ",
)

def _is_slide_label_phrase(phrase: str) -> bool:
    p = phrase.strip().lower()
    if any(p.startswith(s) for s in _LABEL_STARTERS) and len(p.split()) >= 4:
        return True
    return False

def _is_valid_keyphrase(phrase: str) -> bool:
    """Return True when a phrase is a genuine educational concept.
    Rules are fully generic — no domain hardcoding.
    """
    p = phrase.strip().lower()
    if len(p) < 3:
        return False
    if p in _KP_GENERIC_WORDS:
        return False
    if _is_slide_label_phrase(p):
        return False
    words = p.split()
    if words and words[0] in ("this", "that", "these", "those", "its", "their"):
        return False
    if re.fullmatch(r"[\d\s\.\,\-]+", p):
        return False
    return True

# -- Entity labels ------------------------------------------------------------
# Universal academic labels — work for any subject domain.
GLINER_LABELS = [
    "Academic Concept",
    "Theoretical Principle",
    "Technical Term",
    "Process or Method",
    "System or Framework",
    "Formula or Equation",
]
ENTITY_LABELS = GLINER_LABELS

# -- Data model ---------------------------------------------------------------
@dataclass
class Keyphrase:
    phrase:      str
    score:       float
    source_type: str    # heading | bullet | table | caption | body
    slide_id:    str
    doc_id:      str
    appears_in:  str    # sentence containing the phrase

# -- Load models --------------------------------------------------------------
print("Loading GLiNER large-v2.1 on GPU ...")
gliner = GLiNER.from_pretrained(GLINER_MODEL)
print("GLiNER ready.")

print("Loading spaCy en_core_web_sm (sentence segmentation) ...")
nlp = spacy.load("en_core_web_sm")

print("Loading all-MiniLM-L6-v2 (deduplication) ...")
minilm = SentenceTransformer("all-MiniLM-L6-v2")
print("All models ready.")

# -- Helpers ------------------------------------------------------------------
def _assign_source_type(phrase: str, sc) -> str:
    pl = phrase.lower()
    for h in sc.headings:
        if pl in h.lower(): return "heading"
    for b in sc.bullets:
        if pl in b.lower(): return "bullet"
    for t in sc.table_cells:
        if pl in t.lower(): return "table"
    for c in sc.captions:
        if pl in c.lower(): return "caption"
    return "body"

def _find_sentence(phrase: str, text: str) -> str:
    if not text:
        return ""
    doc = nlp(text)
    pl  = phrase.lower()
    for sent in doc.sents:
        if pl in sent.text.lower():
            return sent.text.strip()
    return text[:200]

def _deduplicate(kps: List[Keyphrase]) -> List[Keyphrase]:
    if len(kps) <= 1:
        return kps
    sorted_kps = sorted(kps, key=lambda k: k.score, reverse=True)
    kept: List[Keyphrase] = []
    for kp in sorted_kps:
        emb = minilm.encode(kp.phrase, convert_to_tensor=True)
        is_dup = any(
            float(st_util.cos_sim(
                emb,
                minilm.encode(k.phrase, convert_to_tensor=True)
            )) >= DEDUP_SIM_THRESHOLD
            for k in kept
        )
        if not is_dup:
            kept.append(kp)
    return kept

# -- LLM keyphrase fallback ---------------------------------------------------
# Used ONLY when GLiNER returns 0 phrases on a slide with ≥ 20 words.
# Fires on ~4-6 slides per PDF (table-only slides, very sparse slides).
# Uses the same Groq key as Step 4 — no new dependency.
# Assigned score: 0.40 (below GLiNER confident hits, above noise).

_KP_FALLBACK_SYSTEM = """You are extracting educational keyphrases from a single lecture slide.

Return ONLY a JSON object: {"keyphrases": ["phrase1", "phrase2", ...]}

Rules:
- Maximum 12 phrases.
- Only include named concepts, technical terms, algorithms, data structures,
  or named methods that a student MUST understand from this slide.
- Good examples: "bubble sort", "ArrayList", "dynamic resizing", "FIFO",
  "binarySearch", "hashmap", "null reference", "linked list"
- Do NOT include: generic words (value, type, size, element, method),
  instructional phrases (to construct, any list of, storing a value),
  professor names, university names, course codes, dates, or slide titles.
- If the slide has no educational content, return {"keyphrases": []}
- Return ONLY the JSON object. No explanation."""

_KP_FALLBACK_USER = """SLIDE TEXT:
{slide_text}"""

def _llm_extract_keyphrases(sc) -> List[Keyphrase]:
    """
    LLM fallback for slides where GLiNER returns 0 phrases.
    Self-contained: creates its own Groq client using the environment key
    so this step runs independently of Step 4.
    """
    # Build clean slide text — strip <br> and HTML artifacts
    all_text = " ".join(sc.headings + sc.body_text + sc.bullets + sc.captions)
    table_text = " ".join(
        re.sub(r"<br\s*/?>", " ", c).strip() for c in sc.table_cells
    )
    slide_text = re.sub(r"\s{2,}", " ",
                        (all_text + " " + table_text).strip())
    if not slide_text or len(slide_text.split()) < 10:
        return []

    groq_key = os.environ.get("GROQ_API_KEY", "")
    if not groq_key:
        print(f"    LLM fallback skipped ({sc.slide_id}): GROQ_API_KEY not set")
        return []

    try:
        from langchain_groq import ChatGroq
        from langchain_core.messages import HumanMessage, SystemMessage

        _kp_llm = ChatGroq(
            model="llama-3.3-70b-versatile",
            temperature=0,
            model_kwargs={"response_format": {"type": "json_object"}},
        )
        response = _kp_llm.invoke([
            SystemMessage(content=_KP_FALLBACK_SYSTEM),
            HumanMessage(content=_KP_FALLBACK_USER.format(slide_text=slide_text)),
        ])
        raw = json.loads(response.content)
        phrases = raw.get("keyphrases", [])
        if not isinstance(phrases, list):
            return []
    except Exception as e:
        print(f"    LLM keyphrase fallback error on {sc.slide_id}: {e}")
        return []

    kps: List[Keyphrase] = []
    seen: set = set()
    for phrase in phrases:
        phrase = str(phrase).lower().strip()
        if not phrase or phrase in seen:
            continue
        if not _is_valid_keyphrase(phrase):
            continue
        seen.add(phrase)
        src = _assign_source_type(phrase, sc)
        app = _find_sentence(phrase, sc.clean_text or slide_text)
        kps.append(Keyphrase(
            phrase=phrase,
            score=0.40,          # fixed score — below GLiNER confident, above noise
            source_type=src,
            slide_id=sc.slide_id,
            doc_id=sc.doc_id,
            appears_in=app,
        ))

    kps = _deduplicate(kps)
    kps.sort(key=lambda k: k.score, reverse=True)
    print(f"    LLM fallback: {len(kps)} phrases for {sc.slide_id}")
    return kps[:KEYPHRASE_MAX]

# -- Main extraction ----------------------------------------------------------
def extract_keyphrases(sc) -> List[Keyphrase]:
    if not sc.clean_text.strip():
        return []

    heading_text = " ".join(sc.headings)

    # For table-only slides: pair cells as "METHOD: description." sentences
    # so GLiNER sees them as definition phrases rather than a flat token dump.
    if sc.table_cells and not sc.bullets and not sc.body_text:
        cells = sc.table_cells
        table_text_parts = []
        for idx in range(0, len(cells) - 1, 2):
            k = re.sub(r"<br\s*/?>", " ", cells[idx]).strip()
            v = re.sub(r"<br\s*/?>", " ", cells[idx + 1]).strip()
            if k and v and not _is_noise(k) and not _is_noise(v):
                table_text_parts.append(f"{k}: {v}.")
        if len(cells) % 2 == 1:
            table_text_parts.append(re.sub(r"<br\s*/?>", " ", cells[-1]).strip())
        table_text = " ".join(table_text_parts)
    else:
        table_text = " ".join(
            re.sub(r"<br\s*/?>", " ", c) for c in sc.table_cells
        )

    rest_text = " ".join(sc.body_text + sc.bullets + sc.captions)
    if table_text:
        rest_text = (rest_text + " " + table_text).strip()

    extract_text = (heading_text + ". " + rest_text).strip() \
                   if heading_text and rest_text else (heading_text or rest_text)

    # Strip ALL HTML artifacts before any model sees the text.
    # This fixes the <br> garbage that was causing spaCy to produce broken
    # phrases like ") binarysearch(array" and "sorted tree structure quick sort".
    extract_text = re.sub(r"<[^>]+>", " ", extract_text)
    extract_text = re.sub(r"\s{2,}", " ", extract_text).strip()

    if not extract_text.strip():
        return []

    # ── GLiNER inference ──────────────────────────────────────────────────────
    try:
        entities = gliner.predict_entities(
            extract_text,
            ENTITY_LABELS,
            threshold=GLINER_THRESHOLD,
        )
    except Exception as e:
        print(f"    GLiNER error on {sc.slide_id}: {e}")
        entities = []

    # Collapse duplicate spans — keep highest score per phrase
    best: Dict[str, float] = {}
    for ent in entities:
        phrase = ent["text"].lower().strip()
        score  = float(ent["score"])
        if len(phrase) < 3:
            continue
        if not _is_valid_keyphrase(phrase):
            continue
        if phrase not in best or score > best[phrase]:
            best[phrase] = score

    # Build Keyphrase objects from GLiNER results
    kps: List[Keyphrase] = []
    for phrase, score in best.items():
        src   = _assign_source_type(phrase, sc)
        final = min(score + HEADING_BOOST, 1.0) if src == "heading" else score
        app   = _find_sentence(phrase, sc.clean_text)
        kps.append(Keyphrase(
            phrase=phrase,
            score=round(final, 4),
            source_type=src,
            slide_id=sc.slide_id,
            doc_id=sc.doc_id,
            appears_in=app,
        ))

    kps = _deduplicate(kps)
    kps.sort(key=lambda k: k.score, reverse=True)

    # ── LLM fallback (replaces old spaCy fallback) ────────────────────────────
    # Fires ONLY when GLiNER found nothing AND the slide has real content.
    # The LLM understands context — it won't extract "grocery store" from a
    # queue slide or produce broken tokens from <br>-polluted table text.
    if len(kps) <= 1 and len(extract_text.split()) >= 20:
        kps = _llm_extract_keyphrases(sc)

    return kps[:KEYPHRASE_MAX]

# -- Pedagogical slide filter -------------------------------------------------
# Detects and skips: title slides, ToC/Summary slides, decorative slides.
_TOC_HEADINGS = frozenset({
    "summary", "contents", "outline", "overview", "agenda",
    "topics", "table of contents", "learning objectives",
    "objectives", "what we will cover", "plan", "schedule",
    "recap", "review", "today", "this week", "this lecture",
})

def _is_toc_slide(sc) -> bool:
    """Return True for ToC / overview slides (topic lists with no explanation)."""
    if sc.headings:
        if sc.headings[0].lower().strip() in _TOC_HEADINGS:
            return True
    # Bullet-only slide where every bullet is a short topic name
    has_content = sc.body_text or sc.table_cells or sc.captions
    if not has_content and sc.bullets:
        avg_len = sum(len(b.split()) for b in sc.bullets) / len(sc.bullets)
        if avg_len <= 5 and len(sc.clean_text.split()) < 40:
            return True
    return False

def is_pedagogical_slide(sc) -> bool:
    """Return False for slides with no extractable educational content."""
    word_count = len(sc.clean_text.split())
    if sc.page_number == 1 and word_count < 40:
        return False   # likely title slide
    if word_count < 8:
        return False   # decorative / near-empty
    if _is_toc_slide(sc):
        return False   # ToC / summary
    return True

# -- Run on all pedagogical content slides ------------------------------------
print("\nExtracting keyphrases (GLiNER primary, LLM fallback on 0-result slides) ...")
keyphrases_by_slide: Dict[str, List[Keyphrase]] = {}
label_dist: Dict[str, int] = {}

for i, sc in enumerate(content_slides, 1):
    if not is_pedagogical_slide(sc):
        print(f"  [{i:2d}/{len(content_slides)}] {sc.slide_id}: SKIPPED "
              f"(title/ToC/sparse, {len(sc.clean_text.split())} words)")
        keyphrases_by_slide[sc.slide_id] = []
        continue

    kps = extract_keyphrases(sc)
    keyphrases_by_slide[sc.slide_id] = kps

    # Collect raw entity labels for distribution stats
    raw_text = " ".join(sc.headings + sc.body_text + sc.bullets
                        + sc.table_cells + sc.captions).strip()
    if raw_text:
        try:
            raw_ents = gliner.predict_entities(
                re.sub(r"<[^>]+>", " ", raw_text),
                ENTITY_LABELS,
                threshold=GLINER_THRESHOLD,
            )
            for e in raw_ents:
                label_dist[e["label"]] = label_dist.get(e["label"], 0) + 1
        except Exception:
            pass

    source = "GLiNER" if (kps and kps[0].score > 0.35) else ("LLM" if kps else "none")
    print(f"  [{i:2d}/{len(content_slides)}] {sc.slide_id}: "
          f"{len(kps)} keyphrases [{source}]")
    if kps:
        top3 = ", ".join(f"{k.phrase} ({k.score:.2f})" for k in kps[:3])
        print(f"             top-3: {top3}")

total_kps = sum(len(v) for v in keyphrases_by_slide.values())
print(f"\nStep 3 complete : {total_kps} keyphrases across {len(content_slides)} slides")
print(f"Avg per slide   : {total_kps/len(content_slides):.1f}")
print()
print("Entity label distribution (raw, before dedup):")
for lbl, cnt in sorted(label_dist.items(), key=lambda x: -x[1]):
    print(f"  {lbl:<38} {cnt}")

# -- Save ---------------------------------------------------------------------
STEP3_FILE = f"{STEM}_step3_keyphrases.json"
step3_out  = {sid: [asdict(k) for k in kps]
              for sid, kps in keyphrases_by_slide.items()}
with open(STEP3_FILE, "w", encoding="utf-8") as f:
    json.dump(step3_out, f, ensure_ascii=False, indent=2)
print(f"\nSaved  : {STEP3_FILE} ({Path(STEP3_FILE).stat().st_size:,} bytes)")

# ── Step 3 inspection ─────────────────────────────────────────────────────
from IPython.display import Markdown, display

print(f"{'slide_id':<12}  {'#kps':>4}  top-5 keyphrases (phrase — score — source)")
print("-" * 100)
for sc in content_slides:
    kps = keyphrases_by_slide.get(sc.slide_id, [])
    top5 = ", ".join(
        f"{k.phrase} ({k.score:.2f}/{k.source_type[0]})"
        for k in kps[:5]
    )
    print(f"{sc.slide_id:<12}  {len(kps):>4}  {top5}")

# ── Download Step 3 output ─────────────────────────────────────────────────
from google.colab import files as _files
_files.download(STEP3_FILE)
print(f"Downloading {STEP3_FILE} ...")

import os, json, re, time
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Dict, Optional, Set, Tuple

from sentence_transformers import SentenceTransformer, util as st_util
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

# ── Groq API key ──────────────────────────────────────────────────────────────
from getpass import getpass

GROQ_API_KEY = getpass("Paste your Groq API key (hidden): ")
if not GROQ_API_KEY.strip():
    raise ValueError("GROQ_API_KEY is empty -- cannot proceed with Step 4")
os.environ["GROQ_API_KEY"] = GROQ_API_KEY

# ── Model config ──────────────────────────────────────────────────────────────
LLM_PRIMARY  = "llama-3.3-70b-versatile"
LLM_FALLBACK = "llama-3.1-8b-instant"

# ── Validation thresholds ─────────────────────────────────────────────────────
TRIPLE_CONFIDENCE_THRESHOLD        = 0.70
EVIDENCE_SIMILARITY_THRESHOLD      = 0.65   # for GLiNER-sourced slides
EVIDENCE_SIMILARITY_THRESHOLD_LLM  = 0.50   # relaxed for LLM-sourced slides
# Rationale: slides where ALL keyphrases came from the LLM fallback (score=0.40)
# have flat bullet-list clean_text rather than full sentences. The LLM evidence
# strings for these slides embed less closely to the full slide text, so the
# default 0.65 threshold rejects valid triples. 0.50 still blocks hallucinations.

print("Config ready.")
print(f"  Primary LLM                    : {LLM_PRIMARY}")
print(f"  Fallback LLM                   : {LLM_FALLBACK}")
print(f"  Confidence threshold           : {TRIPLE_CONFIDENCE_THRESHOLD}")
print(f"  Evidence sim threshold (SBERT) : {EVIDENCE_SIMILARITY_THRESHOLD}")
print(f"  Evidence sim threshold (LLM)   : {EVIDENCE_SIMILARITY_THRESHOLD_LLM}")

@dataclass
class Triple:
    subject:    str
    relation:   str
    object:     str
    evidence:   str
    confidence: float
    slide_id:   str
    doc_id:     str
    source:     str = "extraction"

# ── System prompt ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a knowledge graph construction assistant for educational materials.

STRICT RULES -- violating any rule invalidates your entire response:
1. ONLY use concepts from the KEYPHRASE LIST as subject and object. Nothing else.
2. Every triple MUST include an EXACT sentence copied from the SLIDE TEXT as evidence.
3. If no supporting sentence exists in the slide text, omit that triple entirely.
4. Use ONLY these 8 relation types. Follow the DIRECTION rules exactly:

   isPrerequisiteOf   subject must be understood BEFORE object can be understood
                      e.g. "sort --[isPrerequisiteOf]--> binarysearch"
                      (you must sort an array before binary search works on it)

   isDefinedAs        subject IS the concept being defined; object is its definition
                      e.g. "queue --[isDefinedAs]--> fifo"
                      NEVER reverse: concept first, definition second
                      ONE definition per concept — do not repeat with synonyms

   isExampleOf        subject is a SPECIFIC INSTANCE or IMPLEMENTATION of object
                      e.g. "arraylist --[isExampleOf]--> list"
                      e.g. "hashmap --[isExampleOf]--> map"
                      e.g. "bubble sort --[isExampleOf]--> sorting algorithms"
                      USE THIS when X is a named implementation of an interface
                      or a named member of a broader category

   contrastedWith     subject AND object are EXPLICITLY compared or contrasted
                      e.g. "hashmap --[contrastedWith]--> treemap"
                      USE THIS when: slide title has "vs"/"comparison"/"advantages",
                      OR slide text uses "unlike", "whereas", "faster than",
                      "compared to", "better for"

   appliedIn          subject IS USED IN, IS PASSED TO, or OPERATES INSIDE object
                      e.g. "arrays --[appliedIn]--> method"
                      e.g. "comparable --[appliedIn]--> sorting"
                      USE THIS when slide says "X can be passed to Y",
                      "X is used in Y", "X works inside Y"

   isPartOf           subject is a PHYSICAL or STRUCTURAL FIELD/COMPONENT of object
                      e.g. "link --[isPartOf]--> node"
                      e.g. "length --[isPartOf]--> array object"
                      ONLY for literal structural parts: fields of a class,
                      components of a data structure, constants of an object.
                      DO NOT use for: passing/usage, implementations, categories

   causeOf            subject DIRECTLY CAUSES object as a result
                      e.g. "off-by-one error --[causeOf]--> arrayindexoutofboundsexception"

   isGeneralizationOf subject is the BROADER CATEGORY; object is a narrower member
                      e.g. "sorting algorithms --[isGeneralizationOf]--> bubble sort"
                      e.g. "map --[isGeneralizationOf]--> hashmap"
                      The BROADER concept is ALWAYS the subject.

5. CRITICAL DISAMBIGUATION — read every rule before choosing a relation:

   PASSING / USAGE (use appliedIn, NOT isPartOf):
   - "X can be passed to Y"  →  X appliedIn Y
   - "X is used in Y"        →  X appliedIn Y
   - "X works with Y"        →  X appliedIn Y
   - NEVER use isPartOf when the slide is describing passing or usage

   METHOD / OPERATION (use isPartOf for ownership, NOT isExampleOf):
   - If X is a METHOD or OPERATION name (add, remove, enqueue, search):
     → X isPartOf the class/structure it belongs to
     e.g. "add isPartOf arraylist",  "enqueue isPartOf queue"
   - NEVER use isExampleOf for a method or operation name

   IMPLEMENTATION (use isExampleOf, NOT isPartOf):
   - If X is a NAMED IMPLEMENTATION of an interface or abstract concept:
     → X isExampleOf the interface/concept
     e.g. "hashmap isExampleOf map",  "treeset isExampleOf set interface"

   ACRONYM / EXPANSION (only one definition triple per concept):
   - If the keyphrase list contains BOTH an acronym AND its expansion
     (e.g. "fifo" and "first in, first out"), they refer to the SAME concept.
   - Produce ONE isDefinedAs triple using the ACRONYM as subject:
     e.g. "queue isDefinedAs fifo"
   - Do NOT also produce "queue isDefinedAs first in, first out"
   - Do NOT produce isGeneralizationOf or isExampleOf between the acronym
     and its expansion — they are the same concept, not two different ones

   isDefinedAs direction:
   - The NAMED CONCEPT is always the subject.
   - The DEFINITION or DESCRIPTION is the object.
   - "array isDefinedAs ordered list" ✓
   - "ordered list isDefinedAs array" ✗

   isGeneralizationOf direction:
   - The BROADER CATEGORY is the subject, the NARROWER member is the object.
   - "sorting algorithms isGeneralizationOf bubble sort" ✓
   - "bubble sort isGeneralizationOf sorting algorithms" ✗

   Structural membership:
   - If slide says "X consists of Y" / "X has Y" / "X contains Y":
     → Y isPartOf X
   - If slide says "X is a type of Y" / "X is an implementation of Y":
     → X isExampleOf Y

6. DIVERSITY REQUIREMENT:
   - Consider ALL 8 relation types before choosing
   - Do NOT use isPartOf for more than 40% of triples in this response
   - If the slide title contains "vs", "comparison", or "advantages",
     produce at least one contrastedWith triple

7. SLIDE HEADING RULE:
   - The slide title is a topic label, not an educational concept
   - Do NOT use the full slide title as subject or object
   - Use the specific concepts taught within the slide

8. STRUCTURAL LABEL RULE:
   - Do NOT use instructional sub-headings as subject or object:
     e.g. "construction", "storing a value", "to construct an array list"
   - If the keyphrase list contains only such labels, return []

9. DUPLICATE RULE:
   - Do NOT produce two triples with the same (subject, object) pair
   - If you find two valid relations for the same pair, keep only the
     most specific / highest-confidence one
   - Do NOT produce both X isGeneralizationOf Y and Y isExampleOf X
     for the same pair — pick ONE direction

10. Return ONLY a valid JSON array. No markdown, no explanation, no preamble.
11. If no valid triples found, return: []

CRITICAL CONSTRAINTS:
1. NO ADMINISTRATIVE ENTITIES: No people names, universities, course codes, dates.
2. PEDAGOGICAL ONLY: Only academic/domain concepts taught in the material.
3. EMPTY FALLBACK: Title slides, admin slides, ToC slides → return []"""

USER_PROMPT = """KEYPHRASE LIST (subject and object MUST come from this list exactly):
{keyphrases}

SLIDE TEXT:
{slide_text}

Extract all valid triples as a JSON array. Each item:
{{
  "subject": "exact phrase from keyphrase list",
  "relation": "one of the 8 relation types",
  "object": "exact phrase from keyphrase list (different from subject)",
  "evidence": "exact sentence copied from slide text above",
  "confidence": 0.0 to 1.0
}}"""

# ── LLM clients ───────────────────────────────────────────────────────────────
_primary_llm  = None
_fallback_llm = None

def _get_primary() -> ChatGroq:
    global _primary_llm
    if _primary_llm is None:
        _primary_llm = ChatGroq(
            model=LLM_PRIMARY,
            temperature=0,
            model_kwargs={"response_format": {"type": "json_object"}},
        )
    return _primary_llm

def _get_fallback() -> ChatGroq:
    global _fallback_llm
    if _fallback_llm is None:
        _fallback_llm = ChatGroq(
            model=LLM_FALLBACK,
            temperature=0,
            model_kwargs={"response_format": {"type": "json_object"}},
        )
    return _fallback_llm

def _invoke_with_fallback(messages: list, max_retries: int = 3) -> Optional[str]:
    for attempt in range(1, max_retries + 1):
        try:
            return str(_get_primary().invoke(messages).content)
        except Exception as e:
            if "429" in str(e) or "rate" in str(e).lower():
                print(f"    Rate-limited (attempt {attempt}) -- trying fallback ...")
                try:
                    return str(_get_fallback().invoke(messages).content)
                except Exception as e2:
                    if "429" in str(e2) or "rate" in str(e2).lower():
                        print(f"    Fallback also rate-limited -- waiting 5s ...")
                        time.sleep(5)
                        continue
                    print(f"    Fallback error: {e2}")
                    return None
            print(f"    LLM error: {e}")
            return None
    return None

def _parse_llm_response(content: str) -> List[dict]:
    if not content:
        return []
    try:
        raw = json.loads(content)
    except json.JSONDecodeError:
        return []
    if isinstance(raw, list):
        return raw
    if isinstance(raw, dict):
        for v in raw.values():
            if isinstance(v, list):
                return v
    return []

# ── Load SBERT for evidence verification ─────────────────────────────────────
print("Loading all-mpnet-base-v2 for evidence verification ...")
sbert = SentenceTransformer("all-mpnet-base-v2")
print("SBERT ready.")

# ── Valid relations ───────────────────────────────────────────────────────────
_VALID_RELATIONS = frozenset({
    "isPrerequisiteOf", "isDefinedAs", "isExampleOf", "contrastedWith",
    "appliedIn", "isPartOf", "causeOf", "isGeneralizationOf",
})

# ── Structural label detector ─────────────────────────────────────────────────
def _is_structural_label(phrase: str) -> bool:
    """Return True if phrase is an instructional slide label, not a concept."""
    p = phrase.strip().lower()
    _starters = (
        "to ", "any ", "how ", "what ", "when ", "where ", "why ",
        "see ", "let ", "note ", "given ", "recall ", "consider ",
    )
    if any(p.startswith(s) for s in _starters) and len(p.split()) >= 4:
        return True
    # Gerund-led instructional phrases (e.g. "storing a value", "declaring and using")
    words = p.split()
    if words and words[0].endswith("ing") and len(words) >= 3:
        return True
    return False

# ── Build expanded keyphrase lookup set ──────────────────────────────────────
def _build_kp_set(kps) -> Set[str]:
    """
    Build the set of valid keyphrase strings for Layer 1 anchor validation.

    FIX: LLM-extracted keyphrases for method/API slides contain parentheses,
    e.g. 'add(value)', 'get(index)', 'indexOf(value)'.
    When the Step 4 LLM generates a triple it may use the bare name 'add' or
    'get' without parentheses, which would fail a strict set lookup.

    Solution: for every phrase that contains parentheses, also add the
    version with the parentheses and their contents stripped.
    e.g. 'add(value)' → also adds 'add'
         'get(index)' → also adds 'get'
         'binarySearch(array, value)' → also adds 'binarysearch'

    This is one-directional: we expand the lookup set, not the phrase itself,
    so the stored triple subject/object still maps back to the canonical phrase.
    """
    kp_set: Set[str] = set()
    for k in kps:
        p = k.phrase.lower()
        kp_set.add(p)
        # Strip parenthesised argument lists: add(value) → add
        stripped = re.sub(r"\s*\(.*?\)", "", p).strip()
        if stripped and stripped != p and len(stripped) >= 2:
            kp_set.add(stripped)
        # Also strip trailing () with no args: clear() → clear
        no_parens = p.replace("()", "").strip()
        if no_parens and no_parens != p and len(no_parens) >= 2:
            kp_set.add(no_parens)
    return kp_set

def _resolve_phrase(phrase: str, kps) -> str:
    """
    Given a phrase that may be a stripped version (e.g. 'add'), return
    the canonical keyphrase (e.g. 'add(value)') if one exists.
    Falls back to the phrase itself if no match found.
    """
    p = phrase.lower().strip()
    # Direct match first
    for k in kps:
        if k.phrase.lower() == p:
            return k.phrase.lower()
    # Try to find a keyphrase whose stripped form matches
    for k in kps:
        stripped = re.sub(r"\s*\(.*?\)", "", k.phrase.lower()).strip()
        no_parens = k.phrase.lower().replace("()", "").strip()
        if stripped == p or no_parens == p:
            return k.phrase.lower()
    return p

# ── 3-layer validator ─────────────────────────────────────────────────────────
def validate_triple(
    raw: dict,
    kp_set: Set[str],
    kps,
    slide_text: str,
    slide_id: str,
    doc_id: str,
    is_llm_slide: bool = False,
) -> Optional[Triple]:
    """
    Validate a raw LLM-generated triple through 3 layers.

    is_llm_slide: True when ALL keyphrases on this slide came from the LLM
    fallback (score == 0.40).  These slides have flat bullet-list clean_text
    rather than full prose sentences, so the evidence SBERT similarity is
    measured against a lower threshold (EVIDENCE_SIMILARITY_THRESHOLD_LLM)
    to avoid rejecting valid triples due to the terse text structure.
    """
    subject  = str(raw.get("subject",   "")).lower().strip()
    obj      = str(raw.get("object",    "")).lower().strip()
    relation = str(raw.get("relation",  "")).strip()
    evidence = str(raw.get("evidence",  "")).strip()
    try:
        conf = float(raw.get("confidence", 0))
    except (TypeError, ValueError):
        conf = 0.0

    # ── Layer 1: anchor + schema ──────────────────────────────────────────────
    if subject not in kp_set or obj not in kp_set:
        return None
    if subject == obj:
        return None
    if relation not in _VALID_RELATIONS:
        return None
    if _is_structural_label(subject) or _is_structural_label(obj):
        return None

    # Resolve to canonical phrase (handles stripped parentheses)
    subject = _resolve_phrase(subject, kps)
    obj     = _resolve_phrase(obj, kps)
    if subject == obj:
        return None

    # ── Layer 2: evidence verification ────────────────────────────────────────
    if not evidence:
        return None
    ev_emb   = sbert.encode(evidence,   convert_to_tensor=True, show_progress_bar=False)
    text_emb = sbert.encode(slide_text, convert_to_tensor=True, show_progress_bar=False)
    sim = float(st_util.cos_sim(ev_emb, text_emb))
    threshold = EVIDENCE_SIMILARITY_THRESHOLD_LLM if is_llm_slide else EVIDENCE_SIMILARITY_THRESHOLD
    if sim < threshold:
        return None

    # ── Layer 3: confidence threshold ─────────────────────────────────────────
    if conf < TRIPLE_CONFIDENCE_THRESHOLD:
        return None

    return Triple(
        subject=subject, relation=relation, object=obj,
        evidence=evidence, confidence=conf,
        slide_id=slide_id, doc_id=doc_id,
    )

# ── Semantic deduplication helpers ───────────────────────────────────────────
def _phrases_are_synonyms(a: str, b: str) -> bool:
    """
    Return True when two keyphrase strings refer to the same concept and
    should be treated as identical for deduplication purposes.

    Two cases handled — both are generic (no hardcoding):

    1. Acronym / expansion pairs:
       One string is an acronym (short all-alpha, ≤6 chars) and the other
       is its expansion — the acronym matches the first letter of EVERY word
       in the expansion (no stop-word filtering, to handle cases like
       "first in, first out" → f,i,f,o → "fifo").
       e.g. "fifo" vs "first in, first out"
            "lifo" vs "last in, first out"
            "api"  vs "application programming interface"

    2. Substring containment with word-boundary guard:
       One phrase is a clean substring of the other AND the match ends at a
       word boundary (space or end of string) to avoid false positives like
       "array" matching inside "arraylist".
       e.g. "ordered list" vs "ordered list of values" ✓
            "array" vs "arraylist"                     ✗ (no word boundary)
       Capped at 5 words for the shorter phrase.
    """
    a, b = a.lower().strip(), b.lower().strip()
    if a == b:
        return True

    # ── Case 1: acronym / expansion ───────────────────────────────────────────
    def _is_acronym_of(short: str, long: str) -> bool:
        """Return True if `short` is the acronym formed from initials of `long`."""
        short_clean = re.sub(r"[^a-z]", "", short)
        if len(short_clean) < 2 or len(short_clean) > 6:
            return False
        # Use ALL word initials (no stop-word filtering) so that
        # "first in, first out" → [f,i,f,o] → "fifo" matches correctly
        long_words = re.sub(r"[^a-z\s]", "", long).split()
        if not long_words:
            return False
        all_initials = "".join(w[0] for w in long_words if w and w[0].isalpha())
        return short_clean == all_initials

    if _is_acronym_of(a, b) or _is_acronym_of(b, a):
        return True

    # ── Case 2: substring containment with word-boundary guard ────────────────
    shorter, longer = (a, b) if len(a) <= len(b) else (b, a)
    shorter_words = shorter.split()
    if len(shorter_words) < 1 or len(shorter_words) > 5:
        return False
    idx = longer.find(shorter)
    if idx == -1:
        return False
    # Word-boundary check: char immediately after the match must be a space or EOL
    after = longer[idx + len(shorter):]
    if after and after[0] != " ":
        return False   # e.g. "array" inside "arraylist" — next char is "l", not " "
    # Also require they share the same first word
    if not longer.startswith(shorter_words[0]):
        return False
    return True


def _dedup_triples(triples: List[Triple]) -> List[Triple]:
    """
    Deduplicate triples within the same slide.

    Two deduplication passes:

    Pass 1 — Exact pair dedup:
      For any two triples with the same (subject, object) pair, keep only
      the one with the highest confidence. Handles cases where the LLM
      generates both isPartOf and isExampleOf for the same pair.

    Pass 2 — Semantic pair dedup:
      For any two triples where the subjects are synonyms AND the objects
      are synonyms (or vice versa), keep only the higher-confidence one.
      This handles acronym/expansion duplicates like:
        "queue isDefinedAs fifo" + "queue isDefinedAs first in, first out"
      where the two objects mean the same thing but are different strings,
      so Pass 1 would not catch them.

    Both passes are fully generic — no domain-specific knowledge used.
    """
    if not triples:
        return []

    # Pass 1: exact (subject, object) dedup
    best: Dict[Tuple[str, str], Triple] = {}
    for t in triples:
        key = (t.subject, t.object)
        if key not in best or t.confidence > best[key].confidence:
            best[key] = t
    triples = list(best.values())

    # Pass 2: semantic dedup — O(n²) but n is small per slide (≤ 10 triples)
    kept: List[Triple] = []
    for t in sorted(triples, key=lambda x: -x.confidence):
        is_semantic_dup = False
        for k in kept:
            # Same relation, semantically equivalent subject AND object
            subj_match = _phrases_are_synonyms(t.subject, k.subject)
            obj_match  = _phrases_are_synonyms(t.object,  k.object)
            # OR reversed direction (both encode same real-world relationship)
            subj_obj_match = _phrases_are_synonyms(t.subject, k.object)
            obj_subj_match = _phrases_are_synonyms(t.object,  k.subject)
            if (subj_match and obj_match) or (subj_obj_match and obj_subj_match):
                is_semantic_dup = True
                break
        if not is_semantic_dup:
            kept.append(t)

    return kept

# ── Run extraction ────────────────────────────────────────────────────────────
print("\nExtracting triples (1 LLM call per slide) ...")
all_triples: List[Triple] = []
stats = {"slides": 0, "skipped": 0, "raw": 0, "passed": 0, "deduped": 0}

for i, sc in enumerate(content_slides, 1):
    kps = keyphrases_by_slide.get(sc.slide_id, [])
    if not kps or not sc.clean_text.strip():
        print(f"  [{i:2d}/{len(content_slides)}] {sc.slide_id}: skipped (no keyphrases or text)")
        stats["skipped"] += 1
        continue

    # Detect whether ALL keyphrases on this slide came from the LLM fallback.
    # LLM-sourced keyphrases all have score == 0.40 (the fixed LLM fallback score).
    # GLiNER phrases have varying scores above 0.35.
    # This flag is used to select the correct SBERT evidence threshold:
    # LLM slides have flat bullet-list text that embeds differently from prose.
    is_llm_slide = all(k.score == 0.40 for k in kps)

    # Build the keyphrase list shown to the LLM
    kp_list = "\n".join(f"- {k.phrase}" for k in kps)

    # Build expanded lookup set for validation (handles parentheses stripping)
    kp_set = _build_kp_set(kps)

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=USER_PROMPT.format(
            keyphrases=kp_list,
            slide_text=sc.clean_text,
        )),
    ]

    content_raw = _invoke_with_fallback(messages)
    raw_dicts   = _parse_llm_response(content_raw or "")
    stats["raw"] += len(raw_dicts)

    slide_triples: List[Triple] = []
    for rd in raw_dicts:
        t = validate_triple(
            rd, kp_set, kps, sc.clean_text,
            sc.slide_id, sc.doc_id,
            is_llm_slide=is_llm_slide,
        )
        if t is not None:
            slide_triples.append(t)

    # Deduplicate same-pair and semantic-synonym triples within this slide
    before_dedup = len(slide_triples)
    slide_triples = _dedup_triples(slide_triples)
    deduped = before_dedup - len(slide_triples)
    stats["deduped"] += deduped

    all_triples.extend(slide_triples)
    stats["slides"] += 1
    stats["passed"] += len(slide_triples)

    src_label  = "LLM-slide" if is_llm_slide else "SBERT-slide"
    dedup_note = f"  (-{deduped} dups)" if deduped else ""
    print(f"  [{i:2d}/{len(content_slides)}] {sc.slide_id} [{src_label}]: "
          f"{len(raw_dicts)} raw  {len(slide_triples)} valid{dedup_note}")

# ── Final cross-slide deduplication ──────────────────────────────────────────
# A concept pair may appear in multiple slides (e.g. "arraylist" and "list"
# on both the List slide and the Array Lists slide). Keep all of them —
# cross-slide duplicates are fine since they carry different evidence.
# Only deduplicate within the SAME slide (already done above).

print(f"\nStep 4 complete:")
print(f"  Slides processed  : {stats['slides']} (skipped: {stats['skipped']})")
print(f"  Raw candidates    : {stats['raw']}")
if stats["raw"]:
    print(f"  Validated triples : {stats['passed']} "
          f"({100*stats['passed']/stats['raw']:.0f}% pass rate)")
print(f"  Duplicates removed: {stats['deduped']}")

# ── Relation distribution ─────────────────────────────────────────────────────
rel_dist = Counter(t.relation for t in all_triples)
print("\nRelation distribution:")
for rel, cnt in sorted(rel_dist.items(), key=lambda x: -x[1]):
    bar = "█" * cnt
    print(f"  {rel:<22} {cnt:>3}  {bar}")

# ── Save ──────────────────────────────────────────────────────────────────────
STEP4_FILE = f"{STEM}_step4_triples.json"
with open(STEP4_FILE, "w", encoding="utf-8") as f:
    json.dump([asdict(t) for t in all_triples], f, ensure_ascii=False, indent=2)
print(f"\nSaved  : {STEP4_FILE} ({Path(STEP4_FILE).stat().st_size:,} bytes)")

# ── Step 4 inspection ─────────────────────────────────────────────────────
from collections import Counter
from IPython.display import Markdown, display

rel_counts = Counter(t.relation for t in all_triples)

print(f"Total validated triples : {len(all_triples)}")
print(f"\nRelation type distribution:")
for rel, cnt in rel_counts.most_common():
    bar = "█" * cnt
    print(f"  {rel:<22} {cnt:>3}  {bar}")

print("\n" + "=" * 80)
print("Sample triples (first 10):")
for t in all_triples[:10]:
    display(Markdown(
        f"**[{t.slide_id}]** `{t.subject}` —*{t.relation}*→ `{t.object}`  "
        f"conf={t.confidence:.2f}  "
        f"\n> *{t.evidence[:120]}*"
    ))

# ── Download Step 4 output ─────────────────────────────────────────────────
from google.colab import files as _files
_files.download(STEP4_FILE)
print(f"Downloading {STEP4_FILE} ...")

# ── Download all intermediate files at once (optional) ────────────────────
print("\nDownload all intermediate files:")
for fname in [STEP1_FILE, STEP2_FILE, STEP3_FILE, STEP4_FILE]:
    _files.download(fname)
    print(f"  {fname}")
print("Done — check your browser Downloads folder.")